
<ul class="nav nav-pills">
    <li class="active"><a href="#home">Home</a></li>
    <li><a href="#profile">Profile</a></li>
    <li><a href="#messages">Messages</a></li>
</ul>

<div id='content2' class="tab-content">
    <div class="tab-pane active" id="home">
        <ul>
            <li>home</li>
            <li>home</li>
            <li>home</li>
            <li>home</li>
            <li>home</li>
            <li>home</li>
            <li>home</li>
        </ul>
    </div>
    <div class="tab-pane" id="profile">
        <ul>
            <li>profile</li>
            <li>profile</li>
            <li>profile</li>
            <li>profile</li>
            <li>profile</li>
            <li>profile</li>
            <li>profile</li>
        </ul>
    </div>
    <div class="tab-pane" id="messages">
    </div>
    <div class="tab-pane" id="settings"></div>
</div>    



<script type="text/javascript">

<?php $this->headScript()->captureStart(); ?>

    alert('achou java script');
    $('#myTab a').click(function(e) {
        //e.preventDefault();
        $(this).tab('show');
    });







<?php $this->headScript()->captureEnd(); ?>
</script>
