
<div class="container">


    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1>Bem Vindo</h1>
            <p>Texto Boas Vindas</p>
            <p><a class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
        </div>
    </div>


    <footer>
        <p>&copy; Company 2013</p>
    </footer>
</div> <!-- /container -->

