

<div class="panel panel-primary">

    <div class="panel-heading">
        <div class="panel-title">
            Cadastro Grande Gerador de Resíduos           
        </div>
    </div>



    <form d class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('grande-gerador', array('action' => 'adicionar')); ?>">
        <div class="panel-body">
            <div class="row" style="width:700px; height: 300px; float: left">
                <!-- ============Div Situação=================
                    Irá exibir a situação do grande gerador
                    só é exibida quando a situação é diferente de analisando
                -->
                <div id="situacaoCadastro" 
                     style="border:1px solid black; 
                     margin-top: 30px; 
                     margin-bottom:30px; 

                     position: relative;
                     left: 30%;
                     top: 55%;
                     width: 600px; 
                     height: 190px; display:<?php
                     if ($this->habilitaEdicao == 'disabled')
                         echo 'block';
                     else
                         echo 'none';
                     ?>" >
                    <p> <h2 style="text-align: center ">Situação do Cadastro</h2></p>
                    <p> <h3 style="text-align: center "><?php echo $this->escapeHtml($this->form['grande_gerador_situacao']); ?></h3></p>
                    <div style="display: <?php
                    if ($this->form['grande_gerador_situacao'] == 'Pendente')
                        echo 'block';
                    else
                        echo 'none';
                    ?> ">
                        <textarea rows="3" cols="150"  class="form-control "  placeholder="Digite">
                            <?php echo $this->ultimaPendencia->pendencia_descricao; ?> 
 
                        </textarea>


                    </div>
                </div>
                <!-- flag para armazenar o ID do grande gerador -->
                <input  type="hidden" name="grande_gerador_id" class="form-control"   value="<?php echo $this->escapeHtml($this->form['grande_gerador_id']); ?>">
                <!-- flag para armazenar a situação do grande gerador
                     se a situação do grande grande gerador for igual a vazio, a situação recebe analisar
                -->
                <input  type="hidden" name="grande_gerador_situacao" class="form-control"   
                        value="<?php
                        if ($this->form['grande_gerador_situacao'] == '') {
                            echo 'Analisar';
                        } else {
                            echo $this->escapeHtml($this->form['grande_gerador_situacao']);
                        }
                        ?>">
                <!-- 
                    ===============flag para armazenar o ID do residuo para coleta, é usado durante a edição 
                -->
                <input  type="hidden" name="residuo_para_coleta_id" class="form-control" id="inputNomeFantasia" placeholder="Nome Completo" value="<?php echo $this->residuoParaColeta->residuo_para_coleta_id ?>">
                <!-- 
                    =========flag para armazenar a chave estrangeira da empresa prestadora==========
                -->
                <input  type="hidden" name="grande_gerador_fk" class="form-control" id="inputNomeFantasia" placeholder="Nome Completo" value="<?php echo $this->residuoParaColeta->grande_gerador_fk ?>">
                <!-- 
                    ===========flag para armazenar o usuário que esta acessando a tela de autenticação====== 
                -->
                <input  type="hidden" name="usuario" class="form-control" id="inputNomeFantasia" placeholder="Nome Completo" value="<?php echo $this->usuario ?>">
                <!-- 
                    =============flag para armazenar a data do cadastro do grande gerador
                -->
                <div style="display: none">
                    <input  type="datetime" name="grande_gerador_data_cadastro"  id="grande_gerador_data_cadastro"  value="<?php echo $this->escapeHtml($this->form['grande_gerador_data_cadastro']); ?>">
                </div>

                <!-- Inicio inputs do Formulário --> 
                <div class="form-group">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">Nome Fantasia </span>   
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_nome_fantasia" class="form-control" id="grande_gerador_nome_fantasia" placeholder="Digite o Nome Fantasia" value="<?php echo $this->escapeHtml($this->form['grande_gerador_nome_fantasia']); ?>">
                        <span class="input-group-addon">CNPJ</span>
                        <input disabled type="text" name="grande_gerador_cnpj" class="form-control cnpj" id="grande_gerador_cnpj" placeholder="Digite seu telefone principal" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cnpj']); ?>">               
                    </div>
                </div>

                <div class="form-group ">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">Razao Social</span>
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_razao_social" class="form-control" id="grande_gerador_razao_social" placeholder="Digite a Razao Social"  value="<?php echo $this->escapeHtml($this->form['grande_gerador_razao_social']); ?>"> 
                    </div>
                </div>

                <div class="form-group ">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">Ativ. Principal</span>
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_atividade_principal" class="form-control" id="grande_gerador_atividade_principal" placeholder="Digite sua atividade principal" value="<?php echo $this->escapeHtml($this->form['grande_gerador_atividade_principal']); ?>">               
                        <span class="input-group-addon">Código (CNAE)</span>
                        <input <?php echo $this->habilitaEdicao; ?>   type="text" name="grande_gerador_codigo_atividade_principal" class="form-control" id="grande_gerador_codigo_atividade_principal" placeholder="Digite o código (CNAE)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_codigo_atividade_principal']); ?>">               
                    </div>
                </div>
                <div class="form-group ">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">Endereço</span>
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_rua" class="form-control" id="inputTelefoneSecundario" placeholder="Digite o endereço" value="<?php echo $this->escapeHtml($this->form['grande_gerador_rua']); ?>">
                        <span class="input-group-addon">Bairro</span>
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_endereco" class="form-control" id="inputTelefoneSecundario" placeholder="Digite o seu bairro" value="<?php echo $this->escapeHtml($this->form['grande_gerador_endereco']); ?>">
                    </div>
                </div>
                <div class="form-group ">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">Cep</span>
                        <input <?php echo $this->habilitaEdicao; ?>   type="text" name="grande_gerador_cep" class="form-control cep" id="inputTelefoneSecundario" placeholder="Digite o cep" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cep']); ?>">
                        <span class="input-group-addon">Telefone</span>
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_telefone" class="form-control telefone" id="inputTelefoneSecundario" placeholder="Digite seu telefone" value="<?php echo $this->escapeHtml($this->form['grande_gerador_telefone']); ?>">
                    </div>
                </div>
                <div class="form-group ">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">Email</span>
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_email" class="form-control" id="grande_gerador_email" placeholder="Digite seu Email" onblur="validaEmail()" value="<?php echo $this->escapeHtml($this->form['grande_gerador_email']); ?>">
                        <span class="input-group-addon">Responsavel Legal</span>
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_resp_legal" class="form-control" id="inputRespLegal" placeholder="Digite o Responsavel Legal" value="<?php echo $this->escapeHtml($this->form['grande_gerador_resp_legal']); ?>">
                    </div>
                    <div class="col-lg-9  col-md-9"  id="displayEmail" style="display:none; color: red; font-size: 12px;"><label > Email inválido</label></div>
                </div>

                <div class="form-group ">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">Chave de Segurança</span>
                        <input <?php echo $this->habilitaEdicao; ?>  type="PASSWORD" name="grande_gerador_senha" class="form-control" id="grande_gerador_senha"  value="<?php echo $this->escapeHtml($this->form['grande_gerador_senha']); ?>">
                        <span class="input-group-addon">Redigitar Chave de Segurança</span>
                        <input <?php echo $this->habilitaEdicao; ?>  type="PASSWORD" name="grande_gerador_senha_confirmacao" class="form-control" id="grande_gerador_senha_confirmacao" onblur="validaSenha()"  value="<?php echo $this->escapeHtml($this->form['grande_gerador_senha']); ?>">
                    </div>
                    <div class="col-lg-9  col-md-9"  id="displaySenha" style="display:none; color: red;"><label >As Chaves de Segurança não Correspondem</label></div>
                </div>
                <!-- Fim inputs do Formulário grande gerador--> 
            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                    Resíduos Gerados         
                </div>
            </div>
            <div class="corpo-table panel-body">
                <table class="table table-striped table-bordered table-hover" style="font-size: 11px">
                    <thead>
                        <tr>
                            <th>Tipo Residuo</th>
                            <th>Descricao</th>
                            <th>Quantidade Gerada</th>
                            <th>Peso Específico (kg/m3)</th>
                            <th>Tipo de acondicionador</th>  
                            <th>Empresa Prestadora</th>  
                            <th>Local de destinação dos resíduos</th>  
                        </tr>
                    </thead>

                    <tbody>

                        <tr>
                            <td>Umido</td>
                            <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="40" name="residuo_para_coleta_umido_desc" class="form-control " id="inputRespLegal" placeholder="Digite"   ><?php echo $this->residuoParaColeta->residuo_para_coleta_umido_desc ?></textarea></td>
                            <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="2"  name="residuo_para_coleta_umido_qtd_gerada" class="form-control numer" id="inputRespLegal" placeholder="Digite"> <?php echo $this->residuoParaColeta->residuo_para_coleta_umido_qtd_gerada ?></textarea></td>
                            <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="2"  name="residuo_para_coleta_umido_peso" class="form-control numer" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_umido_peso ?></textarea></td>
                            <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="30" name="residuo_para_coleta_umido_tipo_acodic" class="form-control" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_umido_tipo_acodic ?></textarea></td>
                            <td><div class="form-group">

                                    <div >
                                        <!--  Lista as empresas prestadora  -->
                                        <select <?php echo $this->habilitaEdicao; ?>  class="combobox form-control" name="emp_prestadora_fk" id="emp_prestadora_fk" itemscope="4564"  >
                                            <option  value="0"> 
                                                Selecione uma empresa prestadora
                                            </option>
                                            <?php foreach ($this->empresaPrestadora as $tipo_residuo) : ?>
                                                <option  value="<?= $tipo_residuo->emp_prest_id ?>">  <?php echo $this->escapeHtml($tipo_residuo->emp_prest_nome_fantasia); ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                        </td> 

                                    </div>
                                </div>
                            <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="30" name="residuo_para_coleta_umido_local_destinacao" class="form-control" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_umido_local_destinacao ?></textarea></td>

                        </tr>
                        <tr>
                            <td>Secos</td>
                            <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="40" name="residuo_para_coleta_solido_desc" class="form-control " id="inputRespLegal" placeholder="Digite"   ><?php echo $this->residuoParaColeta->residuo_para_coleta_solido_desc ?></textarea></td>
                            <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="2" name="residuo_para_coleta_solido_qtd_gerada" class="form-control numer" id="inputRespLegal" placeholder="Digite"> <?php echo $this->residuoParaColeta->residuo_para_coleta_solido_qtd_gerada ?></textarea></td>
                            <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="2" name="residuo_para_coleta_solido_peso" class="form-control numer" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_solido_peso ?></textarea></td>
                            <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="30" name="residuo_para_coleta_solido_tipo_acodic" class="form-control" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_solido_tipo_acodic ?></textarea></td>
                            <td><label for="inputEmail" class="col-lg-3 col-md-3 control-label" pattern="^@\w{2,}" >Cooperativa</label>
                                <select <?php echo $this->habilitaEdicao; ?>  class="combobox form-control" name="residuo_para_coleta_solido_nome_cooperativa" id="residuo_para_coleta_solido_nome_cooperativa" onclick="analisaCooperativa(this)"   >
                                    <option  value="0">Selecione uma Cooperativa</option>
                                    <option  value="Cooperativa Pega Tudo">Cooperativa Pega Tudo</option>
                                    <option  value="Reciclagem com Qualidade">Reciclagem com Qualidade</option>
                                    <option  value="Qualidade na Reciclagem">Qualidade na Reciclagem</option>
                                    <option  value="Outros">Outros</option>
                                </select>
                            </td>
                            <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="30" name="residuo_para_coleta_solido_local_destinacao" class="form-control" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_solido_local_destinacao ?></textarea></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="panel-footer">

            <button <?php echo $this->habilitaEdicao; ?>  type="submit" class="btn btn-primary" onclick=" validaCadastro(), salvarResiduoBanco()" >Salvar Grande Gerador</button>
            <!--  O botão cancelar irá redirecionar para a página lista grande geradores (página index) 
                se botão cancelar igual a home o botão é exibido
            -->
            <?php
            $bCancelar;
            if ($this->usuario == 'grande_gerador'):
                $bCancelar = 'home';
                ?>
                <a href="<?php echo $this->url($bCancelar) ?>" class="btn btn-default">Cancelar</a>

                <?php
            else:
                $bCancelar = 'index';
                ?>
                <a href="<?php echo $this->url($bCancelar) ?>" class="btn btn-default">Cancelar</a>        
            <?php endif; ?>


        </div>
    </form>
</div>

<script type="text/javascript">

<?php $this->headScript()->captureStart(); ?>

    $(document).ready(function() {


        // jQuery.noConflict();
        // alert('Teste');
        $('.fone').mask('(99) 999-9999'); //telefone
        $('.numer').bind("keyup blur focus", function(e) {
            e.preventDefault();
            var expre = /[^\d]/g;
            $(this).val($(this).val().replace(expre, ''));
        });

        //telefone
        $('cnpj').mask("99.999.999/9999-99");
        $('.cpf').mask("999.999.999-99");
        $('.cpf-sem-underline').mask("999.999.999-99", {placeholder: " "});
        $('.nascimento').mask("99/99/9999");
        $('.placa').mask("aaa-9999");
        $('.cep').mask("99999-999");
        $('.cnpj').mask("99.999.999/9999-99");
        $('.telefone').mask("(99) 9999-9999");
        $('.fax').mask("(99) 9999-9999");
        $('.inscricao-estadual').mask("999.999.999.999");

        //     $('#emp_prestadora_fk').css('border', 'solid 1px red');
        /**
         * Seleciona a empresa prestadora vinculada ao grande gerador
         */
        $('#emp_prestadora_fk').val(<?php echo $this->escapeHtml($this->form['emp_prestadora_fk']); ?>);

        /*
         * se grande_gerador_id for diferente de vazio é selecionado a cooperativa do grande gerador
         * na combox cooperativa
         */
<?php
if ($this->form['grande_gerador_id'] != ''):
    ?>
            $('#residuo_para_coleta_solido_nome_cooperativa').append('<option value="<?php echo $this->residuoParaColeta->residuo_para_coleta_solido_nome_cooperativa ?>" selected="selected"> <?php echo $this->residuoParaColeta->residuo_para_coleta_solido_nome_cooperativa ?> </option>');
<?php endif; ?>


        //  $('#residuo_para_coleta_solido_nome_cooperativa').val(<?php echo $this->residuoParaColeta->residuo_para_coleta_solido_nome_cooperativa ?>);
    });

    var mensagem = '';

    function validaEmail()
    {

        var obj = document.getElementById("grande_gerador_email");
        var txt = obj.value;
        

        if ((txt.length != 0) && ((txt.indexOf("@") < 1) || (txt.indexOf('.') < 7)))
        {
            $('#grande_gerador_email').css('border', 'solid 1px red');
            $("#displayEmail").show();
            // alert('Email incorreto');
            //obj.focus();

            return false;
        }
        else
        {
            $('#grande_gerador_email').css('border', '1px solid #ccc');
            $("#displayEmail").hide();
            return true;
        }

        // alert('Email Inválido!!!');
        // $("#grande_gerador_cnpj").removeAttr("disabled");

    }

    function analisaCooperativa(cooperativa)
    {
        //var outraCooperativa;
        var outraCooperativa;

        if (cooperativa.value == 'Outros')
        {


            do {

                outraCooperativa = prompt("Informe o nome da cooperativa");

            } while (outraCooperativa == null || outraCooperativa == "");

            $('#residuo_para_coleta_solido_nome_cooperativa').append('<option value="' + outraCooperativa + '" selected="selected">' + outraCooperativa + '</option>');

            // var options = $('#residuo_para_coleta_solido_cooperativa').attr('options');
            // options[options.length+1] = new Option('Foo', 'foo', true, true);

            // $("#residuo_para_coleta_solido_cooperativa").val(outraCooperativa);

            //alert(outraCooperativa);
        }

    }

    function validaSenha()
    {
        // alert('valida senha');

        var obj = document.getElementById("grande_gerador_senha");
        var obj2 = document.getElementById("grande_gerador_senha_confirmacao");
        var senha = obj.value;
        var senhaConfirmacao = obj2.value;

        if (senha != senhaConfirmacao)
        {
            // alert('Senhas não  conferem');
            $('#grande_gerador_senha').css('border', 'solid 1px red');
            $("#displaySenha").show();
            $("#grande_gerador_senha").focus();
            // alert('Email incorreto');
            //obj.focus();

            return false;
        }
        else
        {
            $('#grande_gerador_senha').css('border', '1px solid #ccc');
            $("#displaySenha").hide();
            return true;
        }

        // alert('Email Inválido!!!');
        // $("#grande_gerador_cnpj").removeAttr("disabled");

    }

    /*
     * Evetua a busca com filtro 
     */
    function pesquisa()
    {
        $.ajax({
            type: 'post',
            cache: false,
            data: {campo: 2, tipo: 1},
            url: "<?php echo $this->url('grande-gerador', array('action' => 'lista')); ?>",
            // url: '/grande-gerador/lista',
            beforeSend: function() {
            },
            success: function(data) {
                alert('achou php');


                $('#residuo_para_coleta_solido_cooperativa').html(data);
                console.log(data);

            },
            error: function() {
                alert('Nao achou o PHP')
            }
        });
    }
    /**
     * Insere um residuo  na tabela resíduo
     * o valor não é salvo banco de dados
     */


    function atualizaComboResidio(campo) {

        // alert(campo);

        // Função responsável por inserir linhas na tabela
        $("select[name=residuo_para_coleta_solido_cooperativa]").html('<option value="0"> Escolha algo </option>');

        alert(campo);

//        $.ajax({
//            type: "POST",
//            url: "<?php echo $this->url('grande-gerador', array('action' => 'lista')); ?>",
//           // data: "pid=" + id,
//            //dataType: 'json',
//            async: false,
//            success: function(data) {
//                if (data.response) {
//                    alert('achou o php')
//                    //here I want to add a new select  component after select conponent "pid" using like "$this->formRow($form->get('mid'))" or else .   
//                }
//            }
//        });



        $.ajax({
            type: 'post',
            cache: false,
            data: {campo: 2, tipo: 1},
            url: "<?php echo $this->url('grande-gerador', array('action' => 'lista')); ?>",
            // url: '/grande-gerador/lista',
            beforeSend: function() {
            },
            success: function(data) {
                alert('achou php');


                $('#residuo_para_coleta_solido_cooperativa').html(data);
                console.log(data);

            },
            error: function() {
                alert('Nao achou o PHP')
            }
        });


        //  var url = "GrandeGeradorController.php?campo=" + campo;

        // Chamada do método open para processar a requisição
        //  req.open("Get", url, true);


        // document.location.href = "http://www.teste.com.br" + campo.options[campo.selectedIndex].value;
    }

    /*
     * Era usado para salvar um resíduo 
     * quando o resíduo era dividido por tipo
     */
    function salvarResiduoBanco() {

        // alert(campo);


        var table = document.getElementById("tabela_residuos");
        // var selectTipoResiduo = document.getElementById("tipo_residuo_fk") ;
        var selectTipoResiduo = document.getElementById("tipo_residuo_fk").options[document.getElementById("tipo_residuo_fk").selectedIndex].text;
        var selectTipoResiduoCod = document.getElementById("tipo_residuo_fk").value;
        var selectResiduo = document.getElementById("residuo_id").options[document.getElementById("residuo_id").selectedIndex].text; //pega a descrição do resíduo
        var selectResiduoCod = document.getElementById("residuo_id").value; //pega o código do resíduo

        var inputQtdResiduo = document.getElementById("tipo_residuo_fk");
        var inputPesoResiduo = document.getElementById("tipo_residuo_fk");
        // Captura a quantidade de linhas já existentes na tabela
        var numOfRows = table.rows.length;
        // Captura a quantidade de colunas da última linha da tabela
        var numOfCols = table.rows[numOfRows - 1].cells.length;
        // Insere uma linha no fim da tabela.
        var newRow = table.insertRow(numOfRows);

        var numOfCols;

        var residuosHasGerador = new Array();
        // Faz um loop para criar as colunas
        for (var i = 0; i < numOfRows; i++) {
            numOfCols = table.rows[i - 1].cells.length;//captura a primeira linha
            // Insere uma linha no fim da tabela.
            var newRow = table.insertRow(numOfRows);

            for (var j = 0; j < numOfCols; j++) {
                console.log(numOfCols[j].toString());
                // Insere uma coluna na nova linha 
//                residuosHasGerador[0] = table.
//                newCell.
//                // Insere um conteúdo na coluna
//                newCell.innerHTML = "Linha " + numOfRows + " – Coluna " + j;
            }
            event.preventDefault();
        }




        // Função responsável por inserir linhas na tabela
        $("select[name=residuo_fk]").html('<option value="0"> Escolha algo </option>')

        $.ajax({
            type: 'post',
            cache: false,
            data: {campo: campo, tipo: 1},
            url: '/grande-gerador/lista',
            beforeSend: function() {
            },
            success: function(data) {

                $('#residuo_id').html(data);
                console.log(data);

            },
            error: function() {
                alert('Nao achou o PHP')
            }
        });
    }



    function validaCadastro()
    {
        // alert('valida Cadastro');
        emp_prestadora = document.getElementById('emp_prestadora_fk').value;
        email = document.getElementById('emp_prestadora_fk').value;
        $("#grande_gerador_cnpj").removeAttr("disabled");

        // event.preventDefault();
        // nome_fantasia = document.getElementById('grande_gerador_nome_fantasia').value;

        if (!verificaValidacao()) {
            alert(mensagem);
        }

        else
        {
            $("#grande_gerador_cnpj").removeAttr("disabled");
            mensagem = "Deseja salvar os dados ?";
            // variável com resposta da mensagem colocada na janela
            var confirmacao = confirm(mensagem);

            // se a confirmação for false o fluxo é interrompido
            if (!confirmacao)
                // elimar o evendo do botão clicado
                event.preventDefault();
        }


    }



    function verificaValidacao()
    {
        var email = document.getElementById("grande_gerador_email").value;
        var razao_social = document.getElementById("grande_gerador_razao_social").value;
        var nome_fantasia = document.getElementById("grande_gerador_nome_fantasia").value;
        var nome_senha_conf = document.getElementById("grande_gerador_senha_confirmacao").value;

        if (emp_prestadora == 0) {

            event.preventDefault();
            mensagem = 'Selecione um empresa prestadora';
            $("#emp_prestadora_fk").focus();
            return false;
        }



        if ((!validaEmail()) || (email == ''))
        {
            mensagem = 'Email Inválido';
            $("#grande_gerador_email").focus();
            // obj.focus;
            event.preventDefault();
            return false;
        }

        if (nome_fantasia == '')
        {
            mensagem = 'Informa o nome de fantasia';
            $("#grande_gerador_nome_fantasia").focus();
            event.preventDefault();
            return false;
        }
        if (razao_social == '')
        {
            mensagem = 'Informe a razão social';
            $("#grande_gerador_razao_social").focus();
            event.preventDefault();
            return false;
        }
        if (!validaSenha() || nome_senha_conf == '')
        {
            mensagem = 'Senha Inválida';
            $("#grande_gerador_senha").focus();
            event.preventDefault();
            return false;
        }


        return true;
    }



<?php $this->headScript()->captureEnd(); ?>
</script>


