

<div class="panel panel-primary">

    <div class="panel-heading">
        <div class="panel-title">
            Cadastro Grande Gerador de Resíduos           
        </div>
    </div>
    <form d class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('grande-gerador', array('action' => 'adicionar')); ?>">
        <div class="panel-body">
            <div class="form-group"  >

                <input  type="hidden" name="grande_gerador_id" class="form-control"   value="<?php echo $this->escapeHtml($this->form['grande_gerador_id']); ?>">
                <input  type="hidden" name="grande_gerador_situacao" class="form-control"   
                        value="<?php
                        if ($this->form['grande_gerador_situacao'] == '') {
                            echo 'Analisar';
                        } else {
                            echo $this->escapeHtml($this->form['grande_gerador_situacao']);
                        }
                        ?>">
                <input  type="hidden" name="residuo_para_coleta_id" class="form-control" id="inputNomeFantasia" placeholder="Nome Completo" value="<?php echo $this->residuoParaColeta->residuo_para_coleta_id ?>">
                <input  type="hidden" name="grande_gerador_fk" class="form-control" id="inputNomeFantasia" placeholder="Nome Completo" value="<?php echo $this->residuoParaColeta->grande_gerador_fk ?>">
                <input  type="datetime" name="grande_gerador_data_cadastro"  id="grande_gerador_data_cadastro"  value="<?php echo $this->escapeHtml($this->form['grande_gerador_data_cadastro']); ?>">



                <div class="form-group">
                    <label for="inputNomeFantasia" class="col-lg-3 col-md-3 control-label">Nome Fantasia</label>
                    <div class="col-lg-9 col-md-9">
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_nome_fantasia" class="form-control" id="grande_gerador_nome_fantasia" placeholder="Digite o Nome Fantasia" value="<?php echo $this->escapeHtml($this->form['grande_gerador_nome_fantasia']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputRazaoSocial" class="col-lg-3 col-md-3 control-label">Razao Social</label>
                    <div class="col-lg-9  col-md-9">
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_razao_social" class="form-control" id="grande_gerador_razao_social" placeholder="Digite a Razao Social"  value="<?php echo $this->escapeHtml($this->form['grande_gerador_razao_social']); ?>"> 
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputCnpj" class="col-lg-3 col-md-3 control-label">CNPJ</label>
                    <div class="col-lg-9  col-md-9">
                        <input disabled type="text" name="grande_gerador_cnpj" class="form-control cnpj" id="grande_gerador_cnpj" placeholder="Digite seu telefone principal" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cnpj']); ?>">               
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputRua" class="col-lg-3 col-md-3 control-label">Endereço</label>
                    <div class="col-lg-9  col-md-9">
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_rua" class="form-control" id="inputTelefoneSecundario" placeholder="Digite a Rua" value="<?php echo $this->escapeHtml($this->form['grande_gerador_rua']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputBairro" class="col-lg-3 col-md-3 control-label">Bairro</label>
                    <div class="col-lg-9  col-md-9">
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_endereco" class="form-control" id="inputTelefoneSecundario" placeholder="Digite o seu bairro" value="<?php echo $this->escapeHtml($this->form['grande_gerador_endereco']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputCep" class="col-lg-3 col-md-3 control-label">CEP</label>
                    <div class="col-lg-9  col-md-9">
                        <input <?php echo $this->habilitaEdicao; ?>   type="text" name="grande_gerador_cep" class="form-control cep" id="inputTelefoneSecundario" placeholder="Digite o cep" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cep']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputTelefone" class="col-lg-3 col-md-3 control-label">Telefone</label>
                    <div class="col-lg-9  col-md-9">
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_telefone" class="form-control telefone" id="inputTelefoneSecundario" placeholder="Digite seu telefone" value="<?php echo $this->escapeHtml($this->form['grande_gerador_telefone']); ?>">
                    </div>
                </div>

                <div class="form-group">

                    <label for="inputEmail" class="col-lg-3 col-md-3 control-label" pattern="^@\w{2,}" >Email</label>
                    <div class="col-lg-9  col-md-9">
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_email" class="form-control" id="grande_gerador_email" placeholder="Digite seu Email" onblur="validaEmail()" value="<?php echo $this->escapeHtml($this->form['grande_gerador_email']); ?>">
                    </div>
                    <label for="inputEmail" class="col-lg-3 col-md-3 control-label"></label>
                    <div class="col-lg-9  col-md-9"  id="email" style="display:none; color: red;"><label > Email inválido</label></div>

                </div>

                <div class="form-group">
                    <label for="inputRespLegal" class="col-lg-3 col-md-3 control-label">Responsavel Legal</label>
                    <div class="col-lg-9 ">
                        <input <?php echo $this->habilitaEdicao; ?>  type="text" name="grande_gerador_resp_legal" class="form-control" id="inputRespLegal" placeholder="Digite o Responsavel Legal" value="<?php echo $this->escapeHtml($this->form['grande_gerador_resp_legal']); ?>">
                    </div>
                </div>  

                <div class=" form-group">
                    <div class="form-group">
                        <label for="inputRespLegal" class="col-lg-3 col-md-3 control-label">Senha</label>
                        <div class="col-lg-4 ">
                            <input <?php echo $this->habilitaEdicao; ?>  type="PASSWORD" name="grande_gerador_senha" class="form-control" id="grande_gerador_senha"  value="<?php echo $this->escapeHtml($this->form['grande_gerador_senha']); ?>">
                        </div>

                        <label for="inputRespLegal" class="col-lg-1 control-label">Confirmar</label>
                        <div class="col-lg-4 ">
                            <input <?php echo $this->habilitaEdicao; ?>  type="PASSWORD" name="grande_gerador_senha_confirmacao" class="form-control" id="grande_gerador_senha_confirmacao" onblur="validaSenha()"  value="<?php echo $this->escapeHtml($this->form['grande_gerador_senha']); ?>">
                        </div>
                        <div class="col-lg-9  col-md-9"  id="displaySenha" style="display:none; color: red;"><label >A senha não conferi com a confirmação de senha</label></div>
                    </div>

                </div>
            </div>


            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">
                        Resíduos Gerados         
                    </div>
                </div>
                <div class="corpo-table panel-body">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Tipo Residuo</th>
                                <th>Descricao</th>
                                <th>Quantidade Gerada</th>
                                <th>Peso Específico (kg/m3)</th>
                                <th>Tipo de acondicionador</th>  
                                <th>Empresa Prestadora</th>  
                                <th>Local de destinação dos resíduos</th>  
                            </tr>
                        </thead>

                        <tbody>

                            <tr>
                                <td>Umido</td>
                                <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="40" name="residuo_para_coleta_umido_desc" class="form-control " id="inputRespLegal" placeholder="Digite"   ><?php echo $this->residuoParaColeta->residuo_para_coleta_umido_desc ?></textarea></td>
                                <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="2"  name="residuo_para_coleta_umido_qtd_gerada" class="form-control numer" id="inputRespLegal" placeholder="Digite"> <?php echo $this->residuoParaColeta->residuo_para_coleta_umido_qtd_gerada ?></textarea></td>
                                <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="2"  name="residuo_para_coleta_umido_peso" class="form-control numer" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_umido_peso ?></textarea></td>
                                <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="30" name="residuo_para_coleta_umido_tipo_acodic" class="form-control" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_umido_tipo_acodic ?></textarea></td>
                                <td><div class="form-group">

                                        <div >
                                            <!--  Lista as empresas prestadora  -->
                                            <select <?php echo $this->habilitaEdicao; ?>  class="combobox form-control" name="emp_prestadora_fk" id="emp_prestadora_fk" itemscope="4564"  >
                                                <option  value="0"> 
                                                    Selecione uma empresa prestadora
                                                </option>
                                                <?php foreach ($this->empresaPrestadora as $tipo_residuo) : ?>
                                                    <option  value="<?= $tipo_residuo->emp_prest_id ?>">  <?php echo $this->escapeHtml($tipo_residuo->emp_prest_nome_fantasia); ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                            </td> 

                                        </div>
                                    </div>
                                <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="30" name="residuo_para_coleta_umido_local_destinacao" class="form-control" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_umido_local_destinacao ?></textarea></td>

                            </tr>
                            <tr>
                                <td>Secos</td>
                                <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="40" name="residuo_para_coleta_solido_desc" class="form-control " id="inputRespLegal" placeholder="Digite"   ><?php echo $this->residuoParaColeta->residuo_para_coleta_solido_desc ?></textarea></td>
                                <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="2" name="residuo_para_coleta_solido_qtd_gerada" class="form-control numer" id="inputRespLegal" placeholder="Digite"> <?php echo $this->residuoParaColeta->residuo_para_coleta_solido_qtd_gerada ?></textarea></td>
                                <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="2" name="residuo_para_coleta_solido_peso" class="form-control numer" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_solido_peso ?></textarea></td>
                                <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="30" name="residuo_para_coleta_solido_tipo_acodic" class="form-control" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_solido_tipo_acodic ?></textarea></td>
                                <td><label for="inputEmail" class="col-lg-3 col-md-3 control-label" pattern="^@\w{2,}" >Cooperativa</label>
                                    <select <?php echo $this->habilitaEdicao; ?>  class="combobox form-control" name="residuo_para_coleta_solido_cooperativa" id="residuo_para_coleta_solido_cooperativa" onclick="atualizaComboResidio(this)" itemscope="4564"  >
                                        <option  value="0">Selecione uma Cooperativa</option>
                                        <option  value="1">Cooperativa Pega Tudo</option>
                                        <option  value="2">Reciclagem com Qualidade</option>
                                        <option  value="3">Qualidade na Reciclagem</option>
                                    </select>
                                </td>
                                <td><textarea <?php echo $this->habilitaEdicao; ?>  rows="3" cols="30" name="residuo_para_coleta_solido_local_destinacao" class="form-control" id="inputRespLegal" placeholder="Digite"><?php echo $this->residuoParaColeta->residuo_para_coleta_solido_local_destinacao ?></textarea></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="panel-footer">

                <button <?php echo $this->habilitaEdicao; ?>  type="submit" class="btn btn-primary" onclick=" validaCadastro(), salvarResiduoBanco()" >Salvar Grande Gerador</button>
                <!--  O botão cancelar irá redirecionar para a página lista grande geradores (página index) 
                    se botão cancelar igual a home o botão é exibido
                -->
                <div  id="cancelarIndex" style="display:<?php if ($this->botaoCancelar == 'home')
                                                    echo 'block';
                                                else
                                                    echo 'none';
                                                ?>; color: red;">
                    <a href="<?php echo $this->url('home') ?>" class="btn btn-default">Cancelar</a>
                </div>
                <!--  O botão cancelar irá redirecionar para a página lista grande geradores (index) -->
                <div  id="cancelarIndex" style="display:<?php if ($this->botaoCancelar == 'index')
                                                    echo 'block';
                                                else
                                                    echo 'none';
                                                ?>; color: red;">
                    <a href="<?php echo $this->url('grande-gerador') ?>" class="btn btn-default">Cancelar</a>
                </div>
            </div>
    </form>
</div>

<script type="text/javascript">

<?php $this->headScript()->captureStart(); ?>

    $(document).ready(function() {


        // jQuery.noConflict();
        // alert('Teste');
        $('.fone').mask('(99) 999-9999'); //telefone
        $('.numer').bind("keyup blur focus", function(e) {
            e.preventDefault();
            var expre = /[^\d]/g;
            $(this).val($(this).val().replace(expre, ''));
        });

        //telefone
        $('cnpj').mask("99.999.999/9999-99");
        $('.cpf').mask("999.999.999-99");
        $('.cpf-sem-underline').mask("999.999.999-99", {placeholder: " "});
        $('.nascimento').mask("99/99/9999");
        $('.placa').mask("aaa-9999");
        $('.cep').mask("99999-999");
        $('.cnpj').mask("99.999.999/9999-99");
        $('.telefone').mask("(99) 9999-9999");
        $('.fax').mask("(99) 9999-9999");
        $('.inscricao-estadual').mask("999.999.999.999");

        //     $('#emp_prestadora_fk').css('border', 'solid 1px red');
        /**
         * Seleciona a empresa prestadora vinculada ao grande gerador
         */
        $('#emp_prestadora_fk').val(<?php echo $this->escapeHtml($this->form['emp_prestadora_fk']); ?>);

    });

    var mensagem = '';

    function validaEmail()
    {

        var obj = document.getElementById("grande_gerador_email");
        var txt = obj.value;

        if ((txt.length != 0) && ((txt.indexOf("@") < 1) || (txt.indexOf('.') < 7)))
        {
            $('#grande_gerador_email').css('border', 'solid 1px red');
            $("#displaySenha").show();
            // alert('Email incorreto');
            //obj.focus();

            return false;
        }
        else
        {
            $('#grande_gerador_email').css('border', '1px solid #ccc');
            $("#email").hide();
            return true;
        }

        // alert('Email Inválido!!!');
        // $("#grande_gerador_cnpj").removeAttr("disabled");

    }
    function validaSenha()
    {
        // alert('valida senha');

        var obj = document.getElementById("grande_gerador_senha");
        var obj2 = document.getElementById("grande_gerador_senha_confirmacao");
        var senha = obj.value;
        var senhaConfirmacao = obj2.value;

        if (senha != senhaConfirmacao)
        {
            // alert('Senhas não  conferem');
            $('#grande_gerador_senha').css('border', 'solid 1px red');
            $("#displaySenha").show();
            $("#grande_gerador_senha").focus();
            // alert('Email incorreto');
            //obj.focus();

            return false;
        }
        else
        {
            $('#grande_gerador_senha').css('border', '1px solid #ccc');
            $("#displaySenha").hide();
            return true;
        }

        // alert('Email Inválido!!!');
        // $("#grande_gerador_cnpj").removeAttr("disabled");

    }
    
    function pesquisa()
    {
           $.ajax({
            type: 'post',
            cache: false,
             data: {campo: 2, tipo: 1},
            url: "<?php echo $this->url('grande-gerador', array('action' => 'lista')); ?>",
           // url: '/grande-gerador/lista',
            beforeSend: function() {
            },
            success: function(data) {
                alert('achou php');


                $('#residuo_para_coleta_solido_cooperativa').html(data);
                console.log(data);

            },
            error: function() {
                alert('Nao achou o PHP')
            }
        });
    }




    /**
     * Insere um residuo  na tabela resíduo
     * o valor não é salvo banco de dados
     */


    function atualizaComboResidio(campo) {

        // alert(campo);

        // Função responsável por inserir linhas na tabela
        $("select[name=residuo_para_coleta_solido_cooperativa]").html('<option value="0"> Escolha algo </option>');

        alert(campo);

//        $.ajax({
//            type: "POST",
//            url: "<?php echo $this->url('grande-gerador', array('action' => 'lista')); ?>",
//           // data: "pid=" + id,
//            //dataType: 'json',
//            async: false,
//            success: function(data) {
//                if (data.response) {
//                    alert('achou o php')
//                    //here I want to add a new select  component after select conponent "pid" using like "$this->formRow($form->get('mid'))" or else .   
//                }
//            }
//        });



        $.ajax({
            type: 'post',
            cache: false,
             data: {campo: 2, tipo: 1},
            url: "<?php echo $this->url('grande-gerador', array('action' => 'lista')); ?>",
           // url: '/grande-gerador/lista',
            beforeSend: function() {
            },
            success: function(data) {
                alert('achou php');


                $('#residuo_para_coleta_solido_cooperativa').html(data);
                console.log(data);

            },
            error: function() {
                alert('Nao achou o PHP')
            }
        });


        //  var url = "GrandeGeradorController.php?campo=" + campo;

        // Chamada do método open para processar a requisição
        //  req.open("Get", url, true);


        // document.location.href = "http://www.teste.com.br" + campo.options[campo.selectedIndex].value;
    }

    function salvarResiduoBanco() {

        // alert(campo);


        var table = document.getElementById("tabela_residuos");
        // var selectTipoResiduo = document.getElementById("tipo_residuo_fk") ;
        var selectTipoResiduo = document.getElementById("tipo_residuo_fk").options[document.getElementById("tipo_residuo_fk").selectedIndex].text;
        var selectTipoResiduoCod = document.getElementById("tipo_residuo_fk").value;
        var selectResiduo = document.getElementById("residuo_id").options[document.getElementById("residuo_id").selectedIndex].text; //pega a descrição do resíduo
        var selectResiduoCod = document.getElementById("residuo_id").value; //pega o código do resíduo

        var inputQtdResiduo = document.getElementById("tipo_residuo_fk");
        var inputPesoResiduo = document.getElementById("tipo_residuo_fk");
        // Captura a quantidade de linhas já existentes na tabela
        var numOfRows = table.rows.length;
        // Captura a quantidade de colunas da última linha da tabela
        var numOfCols = table.rows[numOfRows - 1].cells.length;
        // Insere uma linha no fim da tabela.
        var newRow = table.insertRow(numOfRows);

        var numOfCols;

        var residuosHasGerador = new Array();
        // Faz um loop para criar as colunas
        for (var i = 0; i < numOfRows; i++) {
            numOfCols = table.rows[i - 1].cells.length;//captura a primeira linha
            // Insere uma linha no fim da tabela.
            var newRow = table.insertRow(numOfRows);

            for (var j = 0; j < numOfCols; j++) {
                console.log(numOfCols[j].toString());
                // Insere uma coluna na nova linha 
//                residuosHasGerador[0] = table.
//                newCell.
//                // Insere um conteúdo na coluna
//                newCell.innerHTML = "Linha " + numOfRows + " – Coluna " + j;
            }
            event.preventDefault();
        }




        // Função responsável por inserir linhas na tabela
        $("select[name=residuo_fk]").html('<option value="0"> Escolha algo </option>')

        $.ajax({
            type: 'post',
            cache: false,
            data: {campo: campo, tipo: 1},
            url: '/grande-gerador/lista',
            beforeSend: function() {
            },
            success: function(data) {

                $('#residuo_id').html(data);
                console.log(data);

            },
            error: function() {
                alert('Nao achou o PHP')
            }
        });
    }



    function validaCadastro()
    {
        // alert('valida Cadastro');
        emp_prestadora = document.getElementById('emp_prestadora_fk').value;
        email = document.getElementById('emp_prestadora_fk').value;
        $("#grande_gerador_cnpj").removeAttr("disabled");
        // nome_fantasia = document.getElementById('grande_gerador_nome_fantasia').value;

        if (!verificaValidacao()) {
            alert(mensagem);
        }

        else
        {
            $("#grande_gerador_cnpj").removeAttr("disabled");
            mensagem = "Deseja salvar os dados ?";
            // variável com resposta da mensagem colocada na janela
            var confirmacao = confirm(mensagem);

            // se a confirmação for false o fluxo é interrompido
            if (!confirmacao)
                // elimar o evendo do botão clicado
                event.preventDefault();
        }


    }



    function verificaValidacao()
    {
        var email = document.getElementById("grande_gerador_email").value;
        var razao_social = document.getElementById("grande_gerador_razao_social").value;
        var nome_fantasia = document.getElementById("grande_gerador_nome_fantasia").value;
        var nome_senha_conf = document.getElementById("grande_gerador_senha_confirmacao").value;

        if (emp_prestadora == 0) {

            event.preventDefault();
            mensagem = 'Selecione um empresa prestadora';
            $("#emp_prestadora_fk").focus();
            return false;
        }



        if ((!validaEmail()) || (email == ''))
        {
            mensagem = 'Email Inválido';
            $("#grande_gerador_email").focus();
            // obj.focus;
            event.preventDefault();
            return false;
        }

        if (nome_fantasia == '')
        {
            mensagem = 'Informa o nome de fantasia';
            $("#grande_gerador_nome_fantasia").focus();
            event.preventDefault();
            return false;
        }
        if (razao_social == '')
        {
            mensagem = 'Informe a razão social';
            $("#grande_gerador_razao_social").focus();
            event.preventDefault();
            return false;
        }
        if (!validaSenha() || nome_senha_conf == '')
        {
            mensagem = 'Senha Inválida';
            $("#grande_gerador_senha").focus();
            event.preventDefault();
            return false;
        }


        return true;
    }



<?php $this->headScript()->captureEnd(); ?>
</script>


