<div class="panel panel-primary">

    <div class="panel-heading">
        <div class="panel-title">
            Tela Cadastro Grande Gerador           
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('grande-gerador', array('action' => 'adicionar')); ?>">
        <div class="panel-body">
            <div class="form-group">

                <div class="form-group">
                    <label for="inputTelefonePrincipal" class="col-lg-3 col-md-3 control-label">Empresa Prestadora</label>
                    <div class="col-lg-9  col-md-9">
                        <select class="combobox" name="emp_prestadora_fk" id="emp_prestadora_fk" itemscope="4564"  >
                            <option  value="0"> 
                                Selecione uma empresa prestadora
                            </option>
                            <?php foreach ($this->empresaPrestadora as $tipo_residuo) : ?>
                                <option  value="<?= $tipo_residuo->emp_prest_id ?>">  <?php echo $this->escapeHtml($tipo_residuo->emp_prest_nome_fantasia); ?></option>
                            <?php endforeach; ?>
                        </select>

                    </div>
                </div>

                <div class="form-group">
                    <label for="inputNomeFantasia" class="col-lg-3 col-md-3 control-label">Nome Fantasia</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="text" name="grande_gerador_nome_fantasia" class="form-control" id="inputNomeFantasia" placeholder="Nome Completo" value="<?php echo $this->escapeHtml($this->form['grande_gerador_nome_fantasia']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputRazaoSocial" class="col-lg-3 col-md-3 control-label">Razão Social</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_razao_social" class="form-control" id="inputRazaoSocial" placeholder="Digite seu telefone principal" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cnpj']); ?>" />      
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputCnpj" class="col-lg-3 col-md-3 control-label">CNPJ</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_cnpj" class="form-control cnpj" id="inputTelefonePrincipal" placeholder="Digite seu telefone principal" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cnpj']); ?>">               
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputRua" class="col-lg-3 col-md-3 control-label">Rua</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_rua" class="form-control" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_rua']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputBairro" class="col-lg-3 col-md-3 control-label">Bairro</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_barro" class="form-control" id="inputTelefoneSecundario" placeholder="Digite o seu bairro(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_barro']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputCep" class="col-lg-3 col-md-3 control-label">CEP</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_cep" class="form-control cep" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cep']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputTelefone" class="col-lg-3 col-md-3 control-label">Telefone</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_telefone" class="form-control telefone" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_telefone']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail" class="col-lg-3 col-md-3 control-label" pattern="^@\w{2,}" >Email</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_email" class="form-control" id="inputEmail" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_email']); ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputRespLegal" class="col-lg-3 col-md-3 control-label">Responsável Legal</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_resp_legal" class="form-control" id="inputRespLegal" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_resp_legal']); ?>">
                    </div>
                </div>  

            </div>
        </div>



        <div class="panel-heading">
            <div class="panel-title">
                Lixo Gerado         
            </div>
        </div>
        <div class="panel-footer" title="Lixo Gerado">
            <div class="panel-body">
                <div class="form-group">
                    <label for="inputTelefonePrincipal" class="col-lg-3 col-md-1 control-label">Tipo Resíduo</label>
                    <select   class="combobox col-lg-2 col-md-2 " name="tipo_residuo_fk" id="tipo_residuo_fk" itemscope="4564" onclick="atualizaComboResidio(document.getElementById('tipo_residuo_fk').value)" >
                        <option  value="0"> 
                            Selecione....
                        </option>
                        <?php foreach ($this->tipoResiduo as $tipo_residuo) : ?>
                            <option  value="<?= $tipo_residuo->tipo_residuo_id ?>">  <?php echo $this->escapeHtml($tipo_residuo->tipo_residuo_nome); ?></option>
                        <?php endforeach; ?>
                    </select>

                    <label for="inputTelefonePrincipal" class="col-lg-1 col-md-1 control-label">   Resíduo</label>
                    <div class="col-lg-1  col-md-2">
                        <select class="combobox" name="residuo_id" id="residuo_id" itemscope="4564"  >
                            <option  value="0"> 
                                Selecione.... 
                            </option>
                            <?php foreach ($this->residuo as $residuo) : ?>
                                <option  value="<?= $residuo->residuo_id ?>">  <?php echo $this->escapeHtml($residuo->residuo_descricao); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>  

            </div>

            <div class="form-group">
                <label for="inputRespLegal" class="col-lg-3 col-md-1 control-label">Quantidade</label>
                <div class="col-lg-2  col-md-2">
                    <input type="text" name="grande_gerador_resp_legal" class="form-control" id="inputRespLegal" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_resp_legal']); ?>">
                </div>
                <label for="inputRespLegal" class="col-lg-0 col-md-1 control-label">Peso</label>
                <div class="col-lg-3  col-md-3">
                    <input type="text" name="grande_gerador_resp_legal" class="form-control" id="inputRespLegal" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_resp_legal']); ?>">
                </div>
            </div>

            <button class="btn-primary col-md-3 col-md-3" title="Inserir Resíduo"  onclick="inserirResiduo()" >
                Inserir Resíduo
            </button>
        </div>


        <div class="form-group">

        </div>  

        <table  class="table table-striped table-bordered table-hover  " title=" Lixo Gerado " id="tabela_residuos" >
            <thead>
                <tr>
                    <th>Tipo Resídio</th>
                    <th>Cod Tr</th>
                    <th>Resídio</th>
                    <th >Cod R</th>
                    <th>Quantidade</th>
                    <th>Peso</th>
                    <th>Ação</th>  
                </tr>
            </thead>

                <tbody id="tabela_residuos">
                <?php foreach ($this->redisudoHasGrandeGerador as $residuoHasGerador) : ?>
                    <tr>
                        
                        <td id="residuos_gerados_grande_gerador_id"><?php echo $this->escapeHtml($residuoHasGerador->residuo_fk_descricao); ?></td>
                        <td id="residuos_gerados_grande_gerador_qtd_dia"><?php echo $this->escapeHtml($residuoHasGerador->residuos_gerados_grande_gerador_qtd_dia); ?></td>
                        <td id="nao_tem_ainda_desc_residuo"><?php echo $this->escapeHtml($residuoHasGerador->residuos_gerados_grande_gerador_peso_espc); ?></td>
                        <td id="residuo_fk"><?php echo $this->escapeHtml($residuoHasGerador->grande_gerador_fk); ?></td>
                        <td id="residuos_gerados_grande_gerador_qtd_dia"><?php echo $this->escapeHtml($residuoHasGerador->residuo_fk); ?></td>
                        <td id="residuos_gerados_grande_gerador_peso_espc"><?php echo $this->escapeHtml($residuoHasGerador->residuo_fk); ?></td>


                        <td> 
                            <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('grande-gerador', array("action" => "deletar", "id" => $residuoHasGerador->residuos_gerados_grande_gerador_id)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

        </table>



        <div class="panel-footer">
            <button type="submit" class="btn btn-primary" onclick="salvarResiduoBanco(), validaCadastro()" >Salvar Grande Gerador</button>
            <a href="<?php echo $this->url('grande-gerador'); ?>" class="btn btn-default">Voltar</a>
        </div>
    </form>
</div>

<script type="text/javascript">

<?php $this->headScript()->captureStart(); ?>

    $(document).ready(function() {


        // jQuery.noConflict();
        // alert('Teste');
        $('.fone').mask('(99) 999-9999'); //telefone
        $('.numer').bind("keyup blur focus", function(e) {
            e.preventDefault();
            var expre = /[^\d]/g;
            $(this).val($(this).val().replace(expre, ''));
        });

        //telefone
        $('cnpj').mask("99.999.999/9999-99");
        $('.cpf').mask("999.999.999-99");
        $('.cpf-sem-underline').mask("999.999.999-99", {placeholder: " "});
        $('.nascimento').mask("99/99/9999");
        $('.placa').mask("aaa-9999");
        $('.cep').mask("99999-999");
        $('.cnpj').mask("99.999.999/9999-99");
        $('.telefone').mask("(99) 9999-9999");
        $('.fax').mask("(99) 9999-9999");
        $('.inscricao-estadual').mask("999.999.999.999");

        //     $('#emp_prestadora_fk').css('border', 'solid 1px red');
        /**
         * Seleciona a empresa prestadora vinculada ao grande gerador
         */
        $('#emp_prestadora_fk').val(<?php echo $this->escapeHtml($this->form['emp_prestadora_fk']); ?>);

    });

    var mensagem = '';

    function validaEmail()
    {

        var obj = document.getElementById("grande_gerador_email");
        var txt = obj.value;

        if ((txt.length != 0) && ((txt.indexOf("@") < 1) || (txt.indexOf('.') < 7)))
        {
            $('#grande_gerador_email').css('border', 'solid 1px red');
            $("#email").show();
            // alert('Email incorreto');
            //obj.focus();

            return false;
        }
        else
        {
            $('#grande_gerador_email').css('border', '1px solid #ccc');
            $("#email").hide();
            return true;
        }

        // alert('Email Inválido!!!');
        // $("#grande_gerador_cnpj").removeAttr("disabled");

    }




    /**
     * Insere um residuo  na tabela resíduo
     * o valor não é salvo banco de dados
     */


    function atualizaComboResidio(campo) {

        alert(campo);

        // Função responsável por inserir linhas na tabela
        $("select[name=residuo_fk]").html('<option value="0"> Escolha algo </option>')


        $.ajax({
            type: 'post',
            cache: false,
            data: {campo: campo, tipo: 1},
            url: '/grande-gerador/lista',
            beforeSend: function() {
            },
            success: function(data) {

                $('#residuo_id').html(data);
                console.log(data);

            },
            error: function() {
                alert('Nao achou o PHP')
            }
        });


        var url = "GrandeGeradorController.php?campo=" + campo;

        // Chamada do método open para processar a requisição
        req.open("Get", url, true);


        // document.location.href = "http://www.teste.com.br" + campo.options[campo.selectedIndex].value;
    }

    function salvarResiduoBanco() {

        // alert(campo);


        var table = document.getElementById("tabela_residuos");
        // var selectTipoResiduo = document.getElementById("tipo_residuo_fk") ;
        var selectTipoResiduo = document.getElementById("tipo_residuo_fk").options[document.getElementById("tipo_residuo_fk").selectedIndex].text;
        var selectTipoResiduoCod = document.getElementById("tipo_residuo_fk").value;
        var selectResiduo = document.getElementById("residuo_id").options[document.getElementById("residuo_id").selectedIndex].text; //pega a descrição do resíduo
        var selectResiduoCod = document.getElementById("residuo_id").value; //pega o código do resíduo

        var inputQtdResiduo = document.getElementById("tipo_residuo_fk");
        var inputPesoResiduo = document.getElementById("tipo_residuo_fk");
        // Captura a quantidade de linhas já existentes na tabela
        var numOfRows = table.rows.length;
        // Captura a quantidade de colunas da última linha da tabela
        var numOfCols = table.rows[numOfRows - 1].cells.length;
        // Insere uma linha no fim da tabela.
        var newRow = table.insertRow(numOfRows);

        var numOfCols;

        var residuosHasGerador = new Array();
        // Faz um loop para criar as colunas
        for (var i = 0; i < numOfRows; i++) {
            numOfCols = table.rows[i - 1].cells.length;//captura a primeira linha
            // Insere uma linha no fim da tabela.
            var newRow = table.insertRow(numOfRows);

            for (var j = 0; j < numOfCols; j++) {
                console.log(numOfCols[j].toString());
                // Insere uma coluna na nova linha 
//                residuosHasGerador[0] = table.
//                newCell.
//                // Insere um conteúdo na coluna
//                newCell.innerHTML = "Linha " + numOfRows + " – Coluna " + j;
            }
            event.preventDefault();
        }




        // Função responsável por inserir linhas na tabela
        $("select[name=residuo_fk]").html('<option value="0"> Escolha algo </option>')

        $.ajax({
            type: 'post',
            cache: false,
            data: {campo: campo, tipo: 1},
            url: '/grande-gerador/lista',
            beforeSend: function() {
            },
            success: function(data) {

                $('#residuo_id').html(data);
                console.log(data);

            },
            error: function() {
                alert('Nao achou o PHP')
            }
        });
    }



    function validaCadastro()
    {
        // alert('valida Cadastro');
        emp_prestadora = document.getElementById('emp_prestadora_fk').value;
        email = document.getElementById('emp_prestadora_fk').value;
        $("#grande_gerador_cnpj").removeAttr("disabled");
        // nome_fantasia = document.getElementById('grande_gerador_nome_fantasia').value;

        if (!verificaValidacao()) {
            alert(mensagem);
        }

        else
        {
            $("#grande_gerador_cnpj").removeAttr("disabled");
            mensagem = "Deseja salvar os dados ?";
            // variável com resposta da mensagem colocada na janela
            var confirmacao = confirm(mensagem);

            // se a confirmação for false o fluxo é interrompido
            if (!confirmacao)
                // elimar o evendo do botão clicado
                event.preventDefault();
        }


    }



    function verificaValidacao()
    {
        var email = document.getElementById("grande_gerador_email").value;
        var razao_social = document.getElementById("grande_gerador_razao_social").value;
        var nome_fantasia = document.getElementById("grande_gerador_nome_fantasia").value;

        if (emp_prestadora == 0) {

            event.preventDefault();
            mensagem = 'Selecione um empresa prestadora';
            return false;
        }



        if ((!validaEmail()) || (email == ''))
        {
            mensagem = 'Email Inválido';
           // obj.focus;
            event.preventDefault();
            return false;
        }

        if (nome_fantasia == '')
        {
            mensagem = 'Informa o nome de fantasia';
            event.preventDefault();
            return false;
        }
        if (razao_social == '')
        {
            mensagem = 'Informe a razão social';
            event.preventDefault();
            return false;
        }


        return true;
    }



<?php $this->headScript()->captureEnd(); ?>
</script>