 <td>18-01-2014</td>    
 <td class="col-lg-2">  
     <select class="col-lg-2 form-control" 
             name="grande_gerador_situacao"
             id="grande_gerador_situacao184"
             itemscope="4564" 
             onclick="atualizaSituacao(document.getElementById('grande_gerador_situacao184','184'))">      <option value="Analisando">Analisando</option>      <option value="Analisar">Analisar</option>      <option value="Analisando">Analisando</option>      <option value="Pendente">Pendente</option>      <option value="Deferido">Deferido</opti