<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">

        <!-- Title Head -->
        <?php
        $NAME_APPLICATION = 'Grande Geradores';
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>

        <!-- Meta Head -->
        <?php
        echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>

        <!-- Styles -->
        <?php
        echo $this
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
               
                ->prependStylesheet($this->basePath() . '/css/style.css')
 
               
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')



        ;
        ?>
        
                <!-- Scripts -->
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/jquery.maskedinput.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
               
                ->prependFile($this->basePath() . '/js/jquery-2.0.3.min.js')
                 ->prependFile($this->basePath() . '/js/bootstrap-modal.js')
                
                ->prependFile($this->basePath() . '/js/funcs.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;

        echo $this->inlineScript();
        ?>
                
        <script type="text/javascript">
            console.log('Oi');
        </script>
        
    </head>
    
    <body>
        <div class="container">
         <!--   <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <?php
                        $url_home = $this->url('home');
                        $url_sobre = $this->url('sobre');
                        $url_grande_gerador = $this->url('grande-gerador');
                       
                        ?>
                        
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->menuAtivo($url_home); ?>"><?php echo $this->translate('Home') ?></a></li>
                           <li <?php echo $this->menuAtivo($url_sobre); ?>>
                                <a href="<?php echo $url_sobre; ?>">Sobre</a>
                            </li>
                           <li <?php echo $this->menuAtivo($url_grande_gerador); ?>>
                                <a href="<?php echo $url_grande_gerador.'/novo'; ?>">Cadastrar Grande Gerador</a>
                            </li>
                           <li <?php echo $this->menuAtivo($url_grande_gerador); ?>>
                                <a href="<?php echo $url_grande_gerador; ?>">Consultar Grande Gerador</a>
                            </li>
                        
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </nav>-->


        

            <div class="row marketing">
                <?php echo $this->content; ?>
            </div>
            
        <script type="text/javascript">
            console.log('Content');
        </script>
        
        
        
            
            
            <!-- menssagem de erro, será exibida no tela. -->
            <?php echo $this->message(); ?>

            <div class="footer">
                <p class="muted credit pull-left">Company <a href="">© 2014</a></p>
                <p class="muted credit pull-right">Desenvolvido por <a href="http://">Cogel</a>.</p>
            </div>
        </div>


    </body>
</html>