<div class="panel panel-primary">

    <div class="panel-heading">
        <div class="panel-title">
            Tela Cadastro Grande Gerador           
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('grande-gerador', array('action' => 'adicionar')); ?>">
        <div class="panel-body">
            <div class="form-group">

                <div class="form-group">
                    <label for="inputTelefonePrincipal" class="col-lg-3 col-md-3 control-label">Empresa Prestadora</label>
                    <div class="col-lg-9  col-md-9">
                        <select class="combobox" name="emp_prestadora_fk" id="emp_prestadora_fk" itemscope="4564"  >
                            <option  value="0"> 
                                Selecione uma empresa prestadora
                            </option>
                            <?php foreach ($this->empresaPrestadora as $tipo_residuo) : ?>
                                <option  value="<?= $tipo_residuo->emp_prest_id ?>">  <?php echo $this->escapeHtml($tipo_residuo->emp_prest_nome_fantasia); ?></option>
                            <?php endforeach; ?>
                        </select>

                    </div>
                </div>

                <div class="form-group">
                    <label for="inputNomeFantasia" class="col-lg-3 col-md-3 control-label">Nome Fantasia</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="text" name="grande_gerador_nome_fantasia" class="form-control" id="inputNomeFantasia" placeholder="Nome Completo" value="<?php echo $this->escapeHtml($this->form['grande_gerador_nome_fantasia']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputRazaoSocial" class="col-lg-3 col-md-3 control-label">Razão Social</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_razao_social" class="form-control" id="inputRazaoSocial" placeholder="Digite seu telefone principal" />      
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputCnpj" class="col-lg-3 col-md-3 control-label">CNPJ</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_cnpj" class="form-control cnpj" id="inputTelefonePrincipal" placeholder="Digite seu telefone principal" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cnpj']); ?>">                </div>
                </div>


                <div class="form-group">
                    <label for="inputRua" class="col-lg-3 col-md-3 control-label">Rua</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_rua" class="form-control" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_rua']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputBairro" class="col-lg-3 col-md-3 control-label">Bairro</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_barro" class="form-control" id="inputTelefoneSecundario" placeholder="Digite o seu bairro(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_barro']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputCep" class="col-lg-3 col-md-3 control-label">CEP</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_cep" class="form-control cep" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cep']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputTelefone" class="col-lg-3 col-md-3 control-label">Telefone</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_telefone" class="form-control telefone" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_telefone']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail" class="col-lg-3 col-md-3 control-label" pattern="^@\w{2,}" >Email</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_email" class="form-control" id="inputEmail" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_email']); ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputRespLegal" class="col-lg-3 col-md-3 control-label">Responsável Legal</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_resp_legal" class="form-control" id="inputRespLegal" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_resp_legal']); ?>">
                    </div>
                </div>  

            </div>
        </div>



        <div class="panel-heading">
            <div class="panel-title">
                Lixo Gerado         
            </div>
        </div>
        <div class="form-group">
            <label for="inputTelefonePrincipal" class="col-lg-3 col-md-1 control-label">Tipo Resíduo</label>
            <div class="col-lg-2  col-md-2">
                <select class="combobox" name="tipo_residuo" id="emp_prestadora_fk" itemscope="4564"  >
                    <option  value="0"> 
                        Selecione o tipo do resíduo 
                    </option>
                    <option  value="">  </option>

                </select>
            </div>

            <label for="inputTelefonePrincipal" class="col-lg-1 col-md-1 control-label">   Resíduo</label>
            <div class="col-md-3  col-md-3">
                <select class="combobox" name="tipo_residuo" id="emp_prestadora_fk" itemscope="4564"  >
                    <option  value="0"> 
                        Selecione o resíduo 
                    </option>

                    <option  value="">  </option>

                </select>
            </div>

        </div>

        <div class="form-group">
            <label for="inputRespLegal" class="col-lg-3 col-md-1 control-label">Quantidade</label>
            <div class="col-lg-2  col-md-2">
                <input type="text" name="grande_gerador_resp_legal" class="form-control" id="inputRespLegal" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_resp_legal']); ?>">
            </div>
            <label for="inputRespLegal" class="col-lg-0 col-md-1 control-label">Peso</label>
            <div class="col-lg-3  col-md-3">
                <input type="text" name="grande_gerador_resp_legal" class="form-control" id="inputRespLegal" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_resp_legal']); ?>">
            </div>
        </div>

        <div class="form-group">

        </div>  
     
            <table class="table table-striped table-bordered table-hover  " title=" Lixo Gerado "  >
                <thead>
                    <tr>
                        <th>Tipo Resídio</th>
                        <th>Resídio</th>
                        <th>Quantidade</th>
                        <th>Peso</th>
                        <th>Ação</th>  
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($this->grandegerador as $tipo_residuo) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($tipo_residuo->grande_gerador_id); ?></td>
                            <td><?php echo $this->escapeHtml($tipo_residuo->grande_gerador_nome_fantasia); ?></td>
                            <td><?php echo $this->escapeHtml($tipo_residuo->grande_gerador_razao_social); ?></td>
                            <td><?php echo $this->escapeHtml($tipo_residuo->grande_gerador_cnpj); ?></td>


                            <td>
                                <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('grande-gerador', array("action" => "detalhes", "id" => $tipo_residuo->grande_gerador_id,)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('grande-gerador', array("action" => "editar", "id" => $tipo_residuo->grande_gerador_id,)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                                <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('grande-gerador', array("action" => "deletar", "id" => $tipo_residuo->grande_gerador_id,)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        


        <div class="panel-footer">
            <button type="submit" class="btn btn-primary" >Salvar Grande Gerador</button>
            <a href="<?php echo $this->url('grande-gerador'); ?>" class="btn btn-default">Voltar</a>
        </div>
    </form>
</div>

<script type="text/javascript">

<?php $this->headScript()->captureStart(); ?>

    $(document).ready(function() {
        // jQuery.noConflict();
        // alert('Teste');

        $('.fone').mask('(99) 999-9999'); //telefone
        $('cnpj').mask("99.999.999/9999-99");
        $('.cpf').mask("999.999.999-99");
        $('.cpf-sem-underline').mask("999.999.999-99", {placeholder: " "});
        $('.nascimento').mask("99/99/9999");
        $('.placa').mask("aaa-9999");
        $('.cep').mask("99999-999");
        $('.cnpj').mask("99.999.999/9999-99");
        $('.telefone').mask("(99) 9999-9999");
        $('.fax').mask("(99) 9999-9999");
        $('.inscricao-estadual').mask("999.999.999.999");

    });

    function chamaURL(campo) {

        alert('Teste');
        document.location.href = "http://www.teste.com.br" + campo.options[campo.selectedIndex].value;
    }


    $(function() {
        // variável para conter a url deletar
        //var url_deletar = '<?php echo $this->url('grande-gerador', array("action" => "deletar")); ?>' + '/';

        // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
//        $('.cpf').focusout((function(event) {
//            // variável contendo o id referente ao botão clicado
//         //   var contato_id = $(this).attr('href').split(url_deletar).pop();
//            // variável contendo mensagem da janela
//            var mensagem = "Deseja realmente apagar o contato de ID " + contato_id + "?";
//            // variável com resposta da mensagem colocada na janela
//            var confirmacao = confirm(mensagem);
//
//            // se a confirmação for false o fluxo é interrompido
//            if (!confirmacao)
//                // elimar o evendo do botão clicado
//                event.preventDefault();
//        });
    });



//        jQuery(function() {
//            jQuery("#cpf").mask("999.999.999-99");
//            jQuery("#cpf-sem-underline").mask("999.999.999-99", {placeholder: " "});
//            jQuery("#nascimento").mask("99/99/9999");
//            jQuery("#placa").mask("aaa-9999");
//            jQuery("#cep").mask("99999-999");
//            jQuery("F#cnpj").mask("99.999.999/9999-99");
//            jQuery("#telefone").mask("(99) 9999-9999");
//            jQuery("#fax").mask("(99) 9999-9999");
//            jQuery("#inscricao-estadual").mask("999.999.999.999");
//        });

<?php $this->headScript()->captureEnd(); ?>

</script>